### ISSUE TITLE
run-android failed?

### ISSUE THREAD

**Issue by lhC0** [ayooby/react-native-calendar-heatmap#15]
Metro Bundler ready.

Loading dependency graph, done.
error: bundling failed: Error: While trying to resolve module `react-native-calendar-heatmap` from file `E:\git\wrd.heimdallr\RN-App\page\js\WindTurbinePage.js`, the package `E:\git\wrd.heimdallr\RN-App\node_modules\react-native-calendar-heatmap\package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`E:\git\wrd.heimdallr\RN-App\node_modules\react-native-calendar-heatmap\lib\src\CalendarHeatmap.js`. Indeed, none of these files exist:

  * `E:\git\wrd.heimdallr\RN-App\node_modules\react-native-calendar-heatmap\lib\src\CalendarHeatmap.js(.native||.android.js|.native.js|.js|.android.json|.native.json|.json)`
  * `E:\git\wrd.heimdallr\RN-App\node_modules\react-native-calendar-heatmap\lib\src\CalendarHeatmap.js\index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json)`
    at ResolutionRequest.resolveDependency (E:\git\wrd.heimdallr\RN-App\node_modules\metro\src\node-haste\DependencyGraph\ResolutionRequest.js:103:15)
    at DependencyGraph.resolveDependency (E:\git\wrd.heimdallr\RN-App\node_modules\metro\src\node-haste\DependencyGraph.js:272:4579)
    at dependencies.map.relativePath (E:\git\wrd.heimdallr\RN-App\node_modules\metro\src\DeltaBundler\traverseDependencies.js:376:19)
    at Array.map (<anonymous>)
    at resolveDependencies (E:\git\wrd.heimdallr\RN-App\node_modules\metro\src\DeltaBundler\traverseDependencies.js:374:16)
    at E:\git\wrd.heimdallr\RN-App\node_modules\metro\src\DeltaBundler\traverseDependencies.js:212:33
    at Generator.next (<anonymous>)
    at step (E:\git\wrd.heimdallr\RN-App\node_modules\metro\src\DeltaBundler\traverseDependencies.js:297:313)
    at E:\git\wrd.heimdallr\RN-App\node_modules\metro\src\DeltaBundler\traverseDependencies.js:297:473
 BUNDLE  [android, dev] ./index.js ▓▓▓▓▓░░░░░░░░░░░ 32.2% (545/960), failed.

**Comment by kuraydev** [comment]
Let me test it to reproduce this issue :)

**Comment by lhC0** [comment]
Sorry, the code can't be sent to you. Please take a look at the possible causes of this problem.Thank you

**Comment by lhC0** [comment]
Sorry, the code can't be sent to you. Please take a look at the possible causes of this problem.Thank you

**Comment by kuraydev** [comment]
I'm going to test it with my own environment. If I could not reproduce it, you should create a minimal reproducible repo for me.

**Comment by kuraydev** [comment]
Hello again @lhC0,
I've tested on my own environment and it works for me. Can you please provide with me a minimal reproducible example/repo?
